// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tftp2.proto

#include "tftp2.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace tftp2 {

inline constexpr PATH::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR PATH::PATH(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PATHDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PATHDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PATHDefaultTypeInternal() {}
  union {
    PATH _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PATHDefaultTypeInternal _PATH_default_instance_;

inline constexpr MOVE::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        old_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        new_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR MOVE::MOVE(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MOVEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MOVEDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MOVEDefaultTypeInternal() {}
  union {
    MOVE _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MOVEDefaultTypeInternal _MOVE_default_instance_;

inline constexpr FILE::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        size_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR FILE::FILE(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FILEDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FILEDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FILEDefaultTypeInternal() {}
  union {
    FILE _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FILEDefaultTypeInternal _FILE_default_instance_;

inline constexpr ListItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : answer_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR ListItem::ListItem(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ListItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListItemDefaultTypeInternal() {}
  union {
    ListItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListItemDefaultTypeInternal _ListItem_default_instance_;

inline constexpr ListResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : items_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListResponse::ListResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ListResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListResponseDefaultTypeInternal() {}
  union {
    ListResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListResponseDefaultTypeInternal _ListResponse_default_instance_;

inline constexpr Mensagem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : tipo_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Mensagem::Mensagem(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MensagemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MensagemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MensagemDefaultTypeInternal() {}
  union {
    Mensagem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MensagemDefaultTypeInternal _Mensagem_default_instance_;
}  // namespace tftp2
static ::_pb::Metadata file_level_metadata_tftp2_2eproto[6];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_tftp2_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_tftp2_2eproto = nullptr;
const ::uint32_t TableStruct_tftp2_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::tftp2::PATH, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::tftp2::PATH, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tftp2::PATH, _impl_.path_),
    0,
    PROTOBUF_FIELD_OFFSET(::tftp2::FILE, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::tftp2::FILE, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tftp2::FILE, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::tftp2::FILE, _impl_.size_),
    0,
    1,
    PROTOBUF_FIELD_OFFSET(::tftp2::MOVE, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::tftp2::MOVE, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tftp2::MOVE, _impl_.old_name_),
    PROTOBUF_FIELD_OFFSET(::tftp2::MOVE, _impl_.new_name_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tftp2::ListResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::tftp2::ListResponse, _impl_.items_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tftp2::ListItem, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::tftp2::ListItem, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::tftp2::ListItem, _impl_.answer_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::tftp2::Mensagem, _internal_metadata_),
    ~0u,  // no _extensions_
    PROTOBUF_FIELD_OFFSET(::tftp2::Mensagem, _impl_._oneof_case_[0]),
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    ::_pbi::kInvalidFieldOffsetTag,
    PROTOBUF_FIELD_OFFSET(::tftp2::Mensagem, _impl_.tipo_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 9, -1, sizeof(::tftp2::PATH)},
        {10, 20, -1, sizeof(::tftp2::FILE)},
        {22, 32, -1, sizeof(::tftp2::MOVE)},
        {34, -1, -1, sizeof(::tftp2::ListResponse)},
        {43, -1, -1, sizeof(::tftp2::ListItem)},
        {54, -1, -1, sizeof(::tftp2::Mensagem)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::tftp2::_PATH_default_instance_._instance,
    &::tftp2::_FILE_default_instance_._instance,
    &::tftp2::_MOVE_default_instance_._instance,
    &::tftp2::_ListResponse_default_instance_._instance,
    &::tftp2::_ListItem_default_instance_._instance,
    &::tftp2::_Mensagem_default_instance_._instance,
};
const char descriptor_table_protodef_tftp2_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013tftp2.proto\022\005tftp2\"\024\n\004PATH\022\014\n\004path\030\001 \002"
    "(\t\"\"\n\004FILE\022\014\n\004name\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\"*"
    "\n\004MOVE\022\020\n\010old_name\030\001 \002(\t\022\020\n\010new_name\030\002 \002"
    "(\t\".\n\014ListResponse\022\036\n\005items\030\001 \003(\0132\017.tftp"
    "2.ListItem\"S\n\010ListItem\022\033\n\004file\030\001 \001(\0132\013.t"
    "ftp2.FILEH\000\022 \n\tdirectory\030\002 \001(\0132\013.tftp2.P"
    "ATHH\000B\010\n\006answer\"\230\001\n\010Mensagem\022\033\n\004list\030\001 \001"
    "(\0132\013.tftp2.PATHH\000\022\033\n\004move\030\002 \001(\0132\013.tftp2."
    "MOVEH\000\022\034\n\005mkdir\030\003 \001(\0132\013.tftp2.PATHH\000\022,\n\r"
    "list_response\030\004 \001(\0132\023.tftp2.ListResponse"
    "H\000B\006\n\004tipo"
};
static ::absl::once_flag descriptor_table_tftp2_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tftp2_2eproto = {
    false,
    false,
    410,
    descriptor_table_protodef_tftp2_2eproto,
    "tftp2.proto",
    &descriptor_table_tftp2_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_tftp2_2eproto::offsets,
    file_level_metadata_tftp2_2eproto,
    file_level_enum_descriptors_tftp2_2eproto,
    file_level_service_descriptors_tftp2_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tftp2_2eproto_getter() {
  return &descriptor_table_tftp2_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tftp2_2eproto(&descriptor_table_tftp2_2eproto);
namespace tftp2 {
// ===================================================================

class PATH::_Internal {
 public:
  using HasBits = decltype(std::declval<PATH>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(PATH, _impl_._has_bits_);
  static void set_has_path(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

PATH::PATH(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.PATH)
}
inline PROTOBUF_NDEBUG_INLINE PATH::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        path_(arena, from.path_) {}

PATH::PATH(
    ::google::protobuf::Arena* arena,
    const PATH& from)
    : ::google::protobuf::Message(arena) {
  PATH* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:tftp2.PATH)
}
inline PROTOBUF_NDEBUG_INLINE PATH::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        path_(arena) {}

inline void PATH::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PATH::~PATH() {
  // @@protoc_insertion_point(destructor:tftp2.PATH)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PATH::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PATH::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.PATH)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.path_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PATH::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 23, 2> PATH::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PATH, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PATH_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // required string path = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(PATH, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string path = 1;
    {PROTOBUF_FIELD_OFFSET(PATH, _impl_.path_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\12\4\0\0\0\0\0\0"
    "tftp2.PATH"
    "path"
  }},
};

::uint8_t* PATH::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.PATH)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string path = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "tftp2.PATH.path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.PATH)
  return target;
}

::size_t PATH::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.PATH)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // required string path = 1;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PATH::_class_data_ = {
    PATH::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PATH::GetClassData() const {
  return &_class_data_;
}

void PATH::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PATH*>(&to_msg);
  auto& from = static_cast<const PATH&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.PATH)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PATH::CopyFrom(const PATH& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.PATH)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PATH::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* PATH::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PATH::InternalSwap(PATH* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata PATH::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[0]);
}
// ===================================================================

class FILE::_Internal {
 public:
  using HasBits = decltype(std::declval<FILE>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(FILE, _impl_._has_bits_);
  static void set_has_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_size(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

FILE::FILE(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.FILE)
}
inline PROTOBUF_NDEBUG_INLINE FILE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        name_(arena, from.name_) {}

FILE::FILE(
    ::google::protobuf::Arena* arena,
    const FILE& from)
    : ::google::protobuf::Message(arena) {
  FILE* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.size_ = from._impl_.size_;

  // @@protoc_insertion_point(copy_constructor:tftp2.FILE)
}
inline PROTOBUF_NDEBUG_INLINE FILE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        name_(arena) {}

inline void FILE::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.size_ = {};
}
FILE::~FILE() {
  // @@protoc_insertion_point(destructor:tftp2.FILE)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FILE::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FILE::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.FILE)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.name_.ClearNonDefaultToEmpty();
  }
  _impl_.size_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FILE::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 23, 2> FILE::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FILE, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FILE_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // required int64 size = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FILE, _impl_.size_), 1>(),
     {16, 1, 0, PROTOBUF_FIELD_OFFSET(FILE, _impl_.size_)}},
    // required string name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(FILE, _impl_.name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string name = 1;
    {PROTOBUF_FIELD_OFFSET(FILE, _impl_.name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required int64 size = 2;
    {PROTOBUF_FIELD_OFFSET(FILE, _impl_.size_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\12\4\0\0\0\0\0\0"
    "tftp2.FILE"
    "name"
  }},
};

::uint8_t* FILE::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.FILE)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string name = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "tftp2.FILE.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required int64 size = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.FILE)
  return target;
}

::size_t FILE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.FILE)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // required string name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_name());
    }

    // required int64 size = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this->_internal_size());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FILE::_class_data_ = {
    FILE::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FILE::GetClassData() const {
  return &_class_data_;
}

void FILE::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FILE*>(&to_msg);
  auto& from = static_cast<const FILE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.FILE)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_name(from._internal_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.size_ = from._impl_.size_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FILE::CopyFrom(const FILE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.FILE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FILE::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* FILE::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FILE::InternalSwap(FILE* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
        swap(_impl_.size_, other->_impl_.size_);
}

::google::protobuf::Metadata FILE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[1]);
}
// ===================================================================

class MOVE::_Internal {
 public:
  using HasBits = decltype(std::declval<MOVE>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(MOVE, _impl_._has_bits_);
  static void set_has_old_name(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_new_name(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

MOVE::MOVE(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.MOVE)
}
inline PROTOBUF_NDEBUG_INLINE MOVE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        old_name_(arena, from.old_name_),
        new_name_(arena, from.new_name_) {}

MOVE::MOVE(
    ::google::protobuf::Arena* arena,
    const MOVE& from)
    : ::google::protobuf::Message(arena) {
  MOVE* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:tftp2.MOVE)
}
inline PROTOBUF_NDEBUG_INLINE MOVE::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        old_name_(arena),
        new_name_(arena) {}

inline void MOVE::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MOVE::~MOVE() {
  // @@protoc_insertion_point(destructor:tftp2.MOVE)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MOVE::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.old_name_.Destroy();
  _impl_.new_name_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MOVE::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.MOVE)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.old_name_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.new_name_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MOVE::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 35, 2> MOVE::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MOVE, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MOVE_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // required string new_name = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(MOVE, _impl_.new_name_)}},
    // required string old_name = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(MOVE, _impl_.old_name_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string old_name = 1;
    {PROTOBUF_FIELD_OFFSET(MOVE, _impl_.old_name_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string new_name = 2;
    {PROTOBUF_FIELD_OFFSET(MOVE, _impl_.new_name_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\12\10\10\0\0\0\0\0"
    "tftp2.MOVE"
    "old_name"
    "new_name"
  }},
};

::uint8_t* MOVE::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.MOVE)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string old_name = 1;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_old_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "tftp2.MOVE.old_name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // required string new_name = 2;
  if (cached_has_bits & 0x00000002u) {
    const std::string& _s = this->_internal_new_name();
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                "tftp2.MOVE.new_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.MOVE)
  return target;
}

::size_t MOVE::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.MOVE)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // required string old_name = 1;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_old_name());
    }

    // required string new_name = 2;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this->_internal_new_name());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MOVE::_class_data_ = {
    MOVE::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MOVE::GetClassData() const {
  return &_class_data_;
}

void MOVE::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MOVE*>(&to_msg);
  auto& from = static_cast<const MOVE&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.MOVE)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_old_name(from._internal_old_name());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_new_name(from._internal_new_name());
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MOVE::CopyFrom(const MOVE& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.MOVE)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MOVE::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) {
    return false;
  }
  return true;
}

::_pbi::CachedSize* MOVE::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MOVE::InternalSwap(MOVE* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.old_name_, &other->_impl_.old_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.new_name_, &other->_impl_.new_name_, arena);
}

::google::protobuf::Metadata MOVE::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[2]);
}
// ===================================================================

class ListResponse::_Internal {
 public:
};

ListResponse::ListResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.ListResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : items_{visibility, arena, from.items_},
        _cached_size_{0} {}

ListResponse::ListResponse(
    ::google::protobuf::Arena* arena,
    const ListResponse& from)
    : ::google::protobuf::Message(arena) {
  ListResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:tftp2.ListResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : items_{visibility, arena},
        _cached_size_{0} {}

inline void ListResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListResponse::~ListResponse() {
  // @@protoc_insertion_point(destructor:tftp2.ListResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ListResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.ListResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ListResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ListResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ListResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .tftp2.ListItem items = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListResponse, _impl_.items_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .tftp2.ListItem items = 1;
    {PROTOBUF_FIELD_OFFSET(ListResponse, _impl_.items_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tftp2::ListItem>()},
  }}, {{
  }},
};

::uint8_t* ListResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.ListResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .tftp2.ListItem items = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_items_size()); i < n; i++) {
    const auto& repfield = this->_internal_items().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.ListResponse)
  return target;
}

::size_t ListResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.ListResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tftp2.ListItem items = 1;
  total_size += 1UL * this->_internal_items_size();
  for (const auto& msg : this->_internal_items()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ListResponse::_class_data_ = {
    ListResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ListResponse::GetClassData() const {
  return &_class_data_;
}

void ListResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ListResponse*>(&to_msg);
  auto& from = static_cast<const ListResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.ListResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(
      from._internal_items());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListResponse::CopyFrom(const ListResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.ListResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ListResponse::IsInitialized() const {
  if (!::google::protobuf::internal::AllAreInitialized(_internal_items()))
    return false;
  return true;
}

::_pbi::CachedSize* ListResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ListResponse::InternalSwap(ListResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
}

::google::protobuf::Metadata ListResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[3]);
}
// ===================================================================

class ListItem::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::tftp2::ListItem, _impl_._oneof_case_);
  static const ::tftp2::FILE& file(const ListItem* msg);
  static const ::tftp2::PATH& directory(const ListItem* msg);
};

const ::tftp2::FILE& ListItem::_Internal::file(const ListItem* msg) {
  return *msg->_impl_.answer_.file_;
}
const ::tftp2::PATH& ListItem::_Internal::directory(const ListItem* msg) {
  return *msg->_impl_.answer_.directory_;
}
void ListItem::set_allocated_file(::tftp2::FILE* file) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_answer();
  if (file) {
    ::google::protobuf::Arena* submessage_arena = file->GetArena();
    if (message_arena != submessage_arena) {
      file = ::google::protobuf::internal::GetOwnedMessage(message_arena, file, submessage_arena);
    }
    set_has_file();
    _impl_.answer_.file_ = file;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.ListItem.file)
}
void ListItem::set_allocated_directory(::tftp2::PATH* directory) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_answer();
  if (directory) {
    ::google::protobuf::Arena* submessage_arena = directory->GetArena();
    if (message_arena != submessage_arena) {
      directory = ::google::protobuf::internal::GetOwnedMessage(message_arena, directory, submessage_arena);
    }
    set_has_directory();
    _impl_.answer_.directory_ = directory;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.ListItem.directory)
}
ListItem::ListItem(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.ListItem)
}
inline PROTOBUF_NDEBUG_INLINE ListItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : answer_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

ListItem::ListItem(
    ::google::protobuf::Arena* arena,
    const ListItem& from)
    : ::google::protobuf::Message(arena) {
  ListItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (answer_case()) {
    case ANSWER_NOT_SET:
      break;
      case kFile:
        _impl_.answer_.file_ = CreateMaybeMessage<::tftp2::FILE>(arena, *from._impl_.answer_.file_);
        break;
      case kDirectory:
        _impl_.answer_.directory_ = CreateMaybeMessage<::tftp2::PATH>(arena, *from._impl_.answer_.directory_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:tftp2.ListItem)
}
inline PROTOBUF_NDEBUG_INLINE ListItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : answer_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void ListItem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListItem::~ListItem() {
  // @@protoc_insertion_point(destructor:tftp2.ListItem)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ListItem::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_answer()) {
    clear_answer();
  }
  _impl_.~Impl_();
}

void ListItem::clear_answer() {
// @@protoc_insertion_point(one_of_clear_start:tftp2.ListItem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (answer_case()) {
    case kFile: {
      if (GetArena() == nullptr) {
        delete _impl_.answer_.file_;
      }
      break;
    }
    case kDirectory: {
      if (GetArena() == nullptr) {
        delete _impl_.answer_.directory_;
      }
      break;
    }
    case ANSWER_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = ANSWER_NOT_SET;
}


PROTOBUF_NOINLINE void ListItem::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.ListItem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_answer();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ListItem::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 2, 0, 2> ListItem::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ListItem_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .tftp2.FILE file = 1;
    {PROTOBUF_FIELD_OFFSET(ListItem, _impl_.answer_.file_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .tftp2.PATH directory = 2;
    {PROTOBUF_FIELD_OFFSET(ListItem, _impl_.answer_.directory_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tftp2::FILE>()},
    {::_pbi::TcParser::GetTable<::tftp2::PATH>()},
  }}, {{
  }},
};

::uint8_t* ListItem::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.ListItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (answer_case()) {
    case kFile: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, _Internal::file(this),
          _Internal::file(this).GetCachedSize(), target, stream);
      break;
    }
    case kDirectory: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::directory(this),
          _Internal::directory(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.ListItem)
  return target;
}

::size_t ListItem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.ListItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (answer_case()) {
    // .tftp2.FILE file = 1;
    case kFile: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.answer_.file_);
      break;
    }
    // .tftp2.PATH directory = 2;
    case kDirectory: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.answer_.directory_);
      break;
    }
    case ANSWER_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ListItem::_class_data_ = {
    ListItem::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ListItem::GetClassData() const {
  return &_class_data_;
}

void ListItem::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ListItem*>(&to_msg);
  auto& from = static_cast<const ListItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.ListItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.answer_case()) {
    case kFile: {
      _this->_internal_mutable_file()->::tftp2::FILE::MergeFrom(
          from._internal_file());
      break;
    }
    case kDirectory: {
      _this->_internal_mutable_directory()->::tftp2::PATH::MergeFrom(
          from._internal_directory());
      break;
    }
    case ANSWER_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListItem::CopyFrom(const ListItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.ListItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ListItem::IsInitialized() const {
  switch (answer_case()) {
    case kFile: {
      if (answer_case() == kFile && !_impl_.answer_.file_->IsInitialized()) return false;
      break;
    }
    case kDirectory: {
      if (answer_case() == kDirectory && !_impl_.answer_.directory_->IsInitialized()) return false;
      break;
    }
    case ANSWER_NOT_SET: {
      break;
    }
  }
  return true;
}

::_pbi::CachedSize* ListItem::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ListItem::InternalSwap(ListItem* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.answer_, other->_impl_.answer_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata ListItem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[4]);
}
// ===================================================================

class Mensagem::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::tftp2::Mensagem, _impl_._oneof_case_);
  static const ::tftp2::PATH& list(const Mensagem* msg);
  static const ::tftp2::MOVE& move(const Mensagem* msg);
  static const ::tftp2::PATH& mkdir(const Mensagem* msg);
  static const ::tftp2::ListResponse& list_response(const Mensagem* msg);
};

const ::tftp2::PATH& Mensagem::_Internal::list(const Mensagem* msg) {
  return *msg->_impl_.tipo_.list_;
}
const ::tftp2::MOVE& Mensagem::_Internal::move(const Mensagem* msg) {
  return *msg->_impl_.tipo_.move_;
}
const ::tftp2::PATH& Mensagem::_Internal::mkdir(const Mensagem* msg) {
  return *msg->_impl_.tipo_.mkdir_;
}
const ::tftp2::ListResponse& Mensagem::_Internal::list_response(const Mensagem* msg) {
  return *msg->_impl_.tipo_.list_response_;
}
void Mensagem::set_allocated_list(::tftp2::PATH* list) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_tipo();
  if (list) {
    ::google::protobuf::Arena* submessage_arena = list->GetArena();
    if (message_arena != submessage_arena) {
      list = ::google::protobuf::internal::GetOwnedMessage(message_arena, list, submessage_arena);
    }
    set_has_list();
    _impl_.tipo_.list_ = list;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.Mensagem.list)
}
void Mensagem::set_allocated_move(::tftp2::MOVE* move) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_tipo();
  if (move) {
    ::google::protobuf::Arena* submessage_arena = move->GetArena();
    if (message_arena != submessage_arena) {
      move = ::google::protobuf::internal::GetOwnedMessage(message_arena, move, submessage_arena);
    }
    set_has_move();
    _impl_.tipo_.move_ = move;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.Mensagem.move)
}
void Mensagem::set_allocated_mkdir(::tftp2::PATH* mkdir) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_tipo();
  if (mkdir) {
    ::google::protobuf::Arena* submessage_arena = mkdir->GetArena();
    if (message_arena != submessage_arena) {
      mkdir = ::google::protobuf::internal::GetOwnedMessage(message_arena, mkdir, submessage_arena);
    }
    set_has_mkdir();
    _impl_.tipo_.mkdir_ = mkdir;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.Mensagem.mkdir)
}
void Mensagem::set_allocated_list_response(::tftp2::ListResponse* list_response) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_tipo();
  if (list_response) {
    ::google::protobuf::Arena* submessage_arena = list_response->GetArena();
    if (message_arena != submessage_arena) {
      list_response = ::google::protobuf::internal::GetOwnedMessage(message_arena, list_response, submessage_arena);
    }
    set_has_list_response();
    _impl_.tipo_.list_response_ = list_response;
  }
  // @@protoc_insertion_point(field_set_allocated:tftp2.Mensagem.list_response)
}
Mensagem::Mensagem(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:tftp2.Mensagem)
}
inline PROTOBUF_NDEBUG_INLINE Mensagem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : tipo_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Mensagem::Mensagem(
    ::google::protobuf::Arena* arena,
    const Mensagem& from)
    : ::google::protobuf::Message(arena) {
  Mensagem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (tipo_case()) {
    case TIPO_NOT_SET:
      break;
      case kList:
        _impl_.tipo_.list_ = CreateMaybeMessage<::tftp2::PATH>(arena, *from._impl_.tipo_.list_);
        break;
      case kMove:
        _impl_.tipo_.move_ = CreateMaybeMessage<::tftp2::MOVE>(arena, *from._impl_.tipo_.move_);
        break;
      case kMkdir:
        _impl_.tipo_.mkdir_ = CreateMaybeMessage<::tftp2::PATH>(arena, *from._impl_.tipo_.mkdir_);
        break;
      case kListResponse:
        _impl_.tipo_.list_response_ = CreateMaybeMessage<::tftp2::ListResponse>(arena, *from._impl_.tipo_.list_response_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:tftp2.Mensagem)
}
inline PROTOBUF_NDEBUG_INLINE Mensagem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : tipo_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Mensagem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Mensagem::~Mensagem() {
  // @@protoc_insertion_point(destructor:tftp2.Mensagem)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Mensagem::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_tipo()) {
    clear_tipo();
  }
  _impl_.~Impl_();
}

void Mensagem::clear_tipo() {
// @@protoc_insertion_point(one_of_clear_start:tftp2.Mensagem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (tipo_case()) {
    case kList: {
      if (GetArena() == nullptr) {
        delete _impl_.tipo_.list_;
      }
      break;
    }
    case kMove: {
      if (GetArena() == nullptr) {
        delete _impl_.tipo_.move_;
      }
      break;
    }
    case kMkdir: {
      if (GetArena() == nullptr) {
        delete _impl_.tipo_.mkdir_;
      }
      break;
    }
    case kListResponse: {
      if (GetArena() == nullptr) {
        delete _impl_.tipo_.list_response_;
      }
      break;
    }
    case TIPO_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = TIPO_NOT_SET;
}


PROTOBUF_NOINLINE void Mensagem::Clear() {
// @@protoc_insertion_point(message_clear_start:tftp2.Mensagem)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_tipo();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Mensagem::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 4, 0, 2> Mensagem::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Mensagem_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .tftp2.PATH list = 1;
    {PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.tipo_.list_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .tftp2.MOVE move = 2;
    {PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.tipo_.move_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .tftp2.PATH mkdir = 3;
    {PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.tipo_.mkdir_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .tftp2.ListResponse list_response = 4;
    {PROTOBUF_FIELD_OFFSET(Mensagem, _impl_.tipo_.list_response_), _Internal::kOneofCaseOffset + 0, 3,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::tftp2::PATH>()},
    {::_pbi::TcParser::GetTable<::tftp2::MOVE>()},
    {::_pbi::TcParser::GetTable<::tftp2::PATH>()},
    {::_pbi::TcParser::GetTable<::tftp2::ListResponse>()},
  }}, {{
  }},
};

::uint8_t* Mensagem::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tftp2.Mensagem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (tipo_case()) {
    case kList: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          1, _Internal::list(this),
          _Internal::list(this).GetCachedSize(), target, stream);
      break;
    }
    case kMove: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, _Internal::move(this),
          _Internal::move(this).GetCachedSize(), target, stream);
      break;
    }
    case kMkdir: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, _Internal::mkdir(this),
          _Internal::mkdir(this).GetCachedSize(), target, stream);
      break;
    }
    case kListResponse: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, _Internal::list_response(this),
          _Internal::list_response(this).GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tftp2.Mensagem)
  return target;
}

::size_t Mensagem::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tftp2.Mensagem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (tipo_case()) {
    // .tftp2.PATH list = 1;
    case kList: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.tipo_.list_);
      break;
    }
    // .tftp2.MOVE move = 2;
    case kMove: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.tipo_.move_);
      break;
    }
    // .tftp2.PATH mkdir = 3;
    case kMkdir: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.tipo_.mkdir_);
      break;
    }
    // .tftp2.ListResponse list_response = 4;
    case kListResponse: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.tipo_.list_response_);
      break;
    }
    case TIPO_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Mensagem::_class_data_ = {
    Mensagem::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* Mensagem::GetClassData() const {
  return &_class_data_;
}

void Mensagem::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Mensagem*>(&to_msg);
  auto& from = static_cast<const Mensagem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:tftp2.Mensagem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.tipo_case()) {
    case kList: {
      _this->_internal_mutable_list()->::tftp2::PATH::MergeFrom(
          from._internal_list());
      break;
    }
    case kMove: {
      _this->_internal_mutable_move()->::tftp2::MOVE::MergeFrom(
          from._internal_move());
      break;
    }
    case kMkdir: {
      _this->_internal_mutable_mkdir()->::tftp2::PATH::MergeFrom(
          from._internal_mkdir());
      break;
    }
    case kListResponse: {
      _this->_internal_mutable_list_response()->::tftp2::ListResponse::MergeFrom(
          from._internal_list_response());
      break;
    }
    case TIPO_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Mensagem::CopyFrom(const Mensagem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tftp2.Mensagem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Mensagem::IsInitialized() const {
  switch (tipo_case()) {
    case kList: {
      if (tipo_case() == kList && !_impl_.tipo_.list_->IsInitialized()) return false;
      break;
    }
    case kMove: {
      if (tipo_case() == kMove && !_impl_.tipo_.move_->IsInitialized()) return false;
      break;
    }
    case kMkdir: {
      if (tipo_case() == kMkdir && !_impl_.tipo_.mkdir_->IsInitialized()) return false;
      break;
    }
    case kListResponse: {
      if (tipo_case() == kListResponse && !_impl_.tipo_.list_response_->IsInitialized()) return false;
      break;
    }
    case TIPO_NOT_SET: {
      break;
    }
  }
  return true;
}

::_pbi::CachedSize* Mensagem::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void Mensagem::InternalSwap(Mensagem* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.tipo_, other->_impl_.tipo_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Mensagem::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tftp2_2eproto_getter, &descriptor_table_tftp2_2eproto_once,
      file_level_metadata_tftp2_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace tftp2
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
